export enum ESecretKey {
  API_KEY = 'API_KEY',
  X_AUTH_VALIDATOR = 'X_AUTH_VALIDATOR',
  NON_EXISTING_SECRET = 'NON_EXISTING_SECRET',
  MANAGEMENT_API_TOKEN = 'MANAGEMENT_API_TOKEN',
  SESSION_JWT_SECRET = 'SESSION_JWT_SECRET',
}
